config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#show'
  resource :user, except: [:new, :create, :destroy]
  get '/room', to: 'rooms#show', as: 'room'
  get '/user', to: 'users#show', as: 'user_profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_rexource_or_scope)
    new_user_session_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'hogehoge' && password == '111111'
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def edit
    @user = current_user
  end

  def updated_at
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報を更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>K-Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <title>Chat Room</title>
    <link rel="stylesheet" href="styles.css">

    <div class="head">
      <h1 class="chat-room-title">Chat room</h1>
      <div class="button-container">
        <% if user_signed_in? %>
          <%= link_to 'マイページ', user_path(current_user), class: 'button'%>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class: 'button' %>
        <% end %>
        <% if !user_signed_in? %>
          <%= link_to 'Sign Up',  new_user_registration_path, class: 'button' %>
        <% end %>       
      </div>
    </div>
    <section class="wave-container">
      <svg class="wave" viewBox="0 0 500 100" preserveAspectRatio="none">
          <path fill="url(#wave-gradient)" d="M0,100 C150,100 350,0 500,100 L500,00 L0,0 Z"></path>
          <defs>
            <linearGradient id="wave-gradient" gradientTransform="rotate(90)">
              <stop offset="0%" stop-color="#ff8484"></stop>
              <stop offset="100%" stop-color="#ffd3a8"></stop>
            </linearGradient>
        </defs>
      </svg>
    </section>
  

  
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<%# views/messages/_message.html.erb %>
<div class="message">
  <p><%= message.content %></p>
</div>

app/views/rooms/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="messages">
    <%= render @messages %>
  </div>
  <ul class="message-list"></ul>
  <div class="send-bar-container">
    <form class="send-bar" action="">
      <input id="input" class="input" autocomplete="off" />
      <button type="submit" class="send-button">送信</button>
    </form>
  </div>
</body>
</html>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
    <h2 class='title'>編集</h2>
      <%= form_for @user, html: { class: "custom-form" } do |f| %>
        <div class="form-group">
          <label>ユーザー名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
          <%= link_to 'チャットルームへ戻る', room_path, class: 'chat-room-button', data: { turbolinks: false } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card cuxtom-card">
        
        <div class="card-body">
          <h5 class="card-title"><%= current_user.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
          <%= link_to 'ユーザー編集', edit_user_path %>
          <%= link_to 'チャットルームへ', room_path, class: 'chat-room-button', data: { turbolinks: false } %>
        </div>
      </div>
    </div>
  </div>
</div>